# Generated by Django 6.0.5 on 2026-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField()),
                ('profesor', models.CharField(max_length=100)),
                ('cupo_maximo', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='curso2/')),
                ('foto_binaria', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
