# Generated by Django 6.0.5 on 2026-05-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="foto",
        ),
    ]

