# Generated by Django 6.0.5 on 2026-05-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0002_remove_curso_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="foto_binaria",
        ),
    ]

